/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgeRouteImport } from './routes/age'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as PinRouteImport } from './routes/pin'
import { Route as PinSetupRouteImport } from './routes/pin-setup'
import { Route as AppAboutRouteImport } from './routes/_app.about'
import { Route as AppCategoryRouteImport } from './routes/_app.category'
import { Route as AppDownloadedRouteImport } from './routes/_app.downloaded'
import { Route as AppExploreRouteImport } from './routes/_app.explore'
import { Route as AppFavoritesRouteImport } from './routes/_app.favorites'
import { Route as AppHistoryRouteImport } from './routes/_app.history'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppLeaderboardRouteImport } from './routes/_app.leaderboard'
import { Route as AppLikedRouteImport } from './routes/_app.liked'
import { Route as AppMyCoursesRouteImport } from './routes/_app.my-courses'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppRedeemRouteImport } from './routes/_app.redeem'
import { Route as AppRedeemHistoryRouteImport } from './routes/_app.redeem-history'
import { Route as AppReelsRouteImport } from './routes/_app.reels'
import { Route as AppSavedRouteImport } from './routes/_app.saved'
import { Route as AppSearchRouteImport } from './routes/_app.search'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppShopRouteImport } from './routes/_app.shop'
import { Route as AppSkillsRouteImport } from './routes/_app.skills'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AppCourseSlugRouteImport } from './routes/_app.course.$slug'
import { Route as AppCreatorUsernameRouteImport } from './routes/_app.creator.$username'
import { Route as AppEnglishCourseIndexRouteImport } from './routes/_app.english-course.index'
import { Route as AppEnglishCourseCourseIdRouteImport } from './routes/_app.english-course.$courseId'
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index'
import { Route as AdminUsersIdRouteImport } from './routes/admin.users.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgeRoute = AgeRouteImport.update({
  id: '/age',
  path: '/age',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const PinRoute = PinRouteImport.update({
  id: '/pin',
  path: '/pin',
  getParentRoute: () => rootRouteImport,
} as any)
const PinSetupRoute = PinSetupRouteImport.update({
  id: '/pin-setup',
  path: '/pin-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoryRoute = AppCategoryRouteImport.update({
  id: '/category',
  path: '/category',
  getParentRoute: () => AppRoute,
} as any)
const AppDownloadedRoute = AppDownloadedRouteImport.update({
  id: '/downloaded',
  path: '/downloaded',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritesRoute = AppFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppLikedRoute = AppLikedRouteImport.update({
  id: '/liked',
  path: '/liked',
  getParentRoute: () => AppRoute,
} as any)
const AppMyCoursesRoute = AppMyCoursesRouteImport.update({
  id: '/my-courses',
  path: '/my-courses',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppRedeemRoute = AppRedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => AppRoute,
} as any)
const AppRedeemHistoryRoute = AppRedeemHistoryRouteImport.update({
  id: '/redeem-history',
  path: '/redeem-history',
  getParentRoute: () => AppRoute,
} as any)
const AppReelsRoute = AppReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => AppRoute,
} as any)
const AppSavedRoute = AppSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppShopRoute = AppShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AppRoute,
} as any)
const AppSkillsRoute = AppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AppCourseSlugRoute = AppCourseSlugRouteImport.update({
  id: '/course/$slug',
  path: '/course/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppCreatorUsernameRoute = AppCreatorUsernameRouteImport.update({
  id: '/creator/$username',
  path: '/creator/$username',
  getParentRoute: () => AppRoute,
} as any)
const AppEnglishCourseIndexRoute = AppEnglishCourseIndexRouteImport.update({
  id: '/english-course/',
  path: '/english-course/',
  getParentRoute: () => AppRoute,
} as any)
const AppEnglishCourseCourseIdRoute =
  AppEnglishCourseCourseIdRouteImport.update({
    id: '/english-course/$courseId',
    path: '/english-course/$courseId',
    getParentRoute: () => AppRoute,
  } as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/age': typeof AgeRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/pin': typeof PinRoute
  '/pin-setup': typeof PinSetupRoute
  '/about': typeof AppAboutRoute
  '/category': typeof AppCategoryRoute
  '/downloaded': typeof AppDownloadedRoute
  '/explore': typeof AppExploreRoute
  '/favorites': typeof AppFavoritesRoute
  '/history': typeof AppHistoryRoute
  '/home': typeof AppHomeRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/liked': typeof AppLikedRoute
  '/my-courses': typeof AppMyCoursesRoute
  '/profile': typeof AppProfileRoute
  '/redeem': typeof AppRedeemRoute
  '/redeem-history': typeof AppRedeemHistoryRoute
  '/reels': typeof AppReelsRoute
  '/saved': typeof AppSavedRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/shop': typeof AppShopRoute
  '/skills': typeof AppSkillsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/course/$slug': typeof AppCourseSlugRoute
  '/creator/$username': typeof AppCreatorUsernameRoute
  '/english-course/$courseId': typeof AppEnglishCourseCourseIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/english-course/': typeof AppEnglishCourseIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/age': typeof AgeRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/pin': typeof PinRoute
  '/pin-setup': typeof PinSetupRoute
  '/about': typeof AppAboutRoute
  '/category': typeof AppCategoryRoute
  '/downloaded': typeof AppDownloadedRoute
  '/explore': typeof AppExploreRoute
  '/favorites': typeof AppFavoritesRoute
  '/history': typeof AppHistoryRoute
  '/home': typeof AppHomeRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/liked': typeof AppLikedRoute
  '/my-courses': typeof AppMyCoursesRoute
  '/profile': typeof AppProfileRoute
  '/redeem': typeof AppRedeemRoute
  '/redeem-history': typeof AppRedeemHistoryRoute
  '/reels': typeof AppReelsRoute
  '/saved': typeof AppSavedRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/shop': typeof AppShopRoute
  '/skills': typeof AppSkillsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/course/$slug': typeof AppCourseSlugRoute
  '/creator/$username': typeof AppCreatorUsernameRoute
  '/english-course/$courseId': typeof AppEnglishCourseCourseIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/english-course': typeof AppEnglishCourseIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/age': typeof AgeRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/pin': typeof PinRoute
  '/pin-setup': typeof PinSetupRoute
  '/_app/about': typeof AppAboutRoute
  '/_app/category': typeof AppCategoryRoute
  '/_app/downloaded': typeof AppDownloadedRoute
  '/_app/explore': typeof AppExploreRoute
  '/_app/favorites': typeof AppFavoritesRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/leaderboard': typeof AppLeaderboardRoute
  '/_app/liked': typeof AppLikedRoute
  '/_app/my-courses': typeof AppMyCoursesRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/redeem': typeof AppRedeemRoute
  '/_app/redeem-history': typeof AppRedeemHistoryRoute
  '/_app/reels': typeof AppReelsRoute
  '/_app/saved': typeof AppSavedRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/shop': typeof AppShopRoute
  '/_app/skills': typeof AppSkillsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/course/$slug': typeof AppCourseSlugRoute
  '/_app/creator/$username': typeof AppCreatorUsernameRoute
  '/_app/english-course/$courseId': typeof AppEnglishCourseCourseIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/_app/english-course/': typeof AppEnglishCourseIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/age'
    | '/login'
    | '/maintenance'
    | '/pin'
    | '/pin-setup'
    | '/about'
    | '/category'
    | '/downloaded'
    | '/explore'
    | '/favorites'
    | '/history'
    | '/home'
    | '/leaderboard'
    | '/liked'
    | '/my-courses'
    | '/profile'
    | '/redeem'
    | '/redeem-history'
    | '/reels'
    | '/saved'
    | '/search'
    | '/settings'
    | '/shop'
    | '/skills'
    | '/admin/settings'
    | '/admin/'
    | '/course/$slug'
    | '/creator/$username'
    | '/english-course/$courseId'
    | '/admin/users/$id'
    | '/english-course/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/age'
    | '/login'
    | '/maintenance'
    | '/pin'
    | '/pin-setup'
    | '/about'
    | '/category'
    | '/downloaded'
    | '/explore'
    | '/favorites'
    | '/history'
    | '/home'
    | '/leaderboard'
    | '/liked'
    | '/my-courses'
    | '/profile'
    | '/redeem'
    | '/redeem-history'
    | '/reels'
    | '/saved'
    | '/search'
    | '/settings'
    | '/shop'
    | '/skills'
    | '/admin/settings'
    | '/admin'
    | '/course/$slug'
    | '/creator/$username'
    | '/english-course/$courseId'
    | '/admin/users/$id'
    | '/english-course'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/age'
    | '/login'
    | '/maintenance'
    | '/pin'
    | '/pin-setup'
    | '/_app/about'
    | '/_app/category'
    | '/_app/downloaded'
    | '/_app/explore'
    | '/_app/favorites'
    | '/_app/history'
    | '/_app/home'
    | '/_app/leaderboard'
    | '/_app/liked'
    | '/_app/my-courses'
    | '/_app/profile'
    | '/_app/redeem'
    | '/_app/redeem-history'
    | '/_app/reels'
    | '/_app/saved'
    | '/_app/search'
    | '/_app/settings'
    | '/_app/shop'
    | '/_app/skills'
    | '/admin/settings'
    | '/admin/'
    | '/_app/course/$slug'
    | '/_app/creator/$username'
    | '/_app/english-course/$courseId'
    | '/admin/users/$id'
    | '/_app/english-course/'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AgeRoute: typeof AgeRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  PinRoute: typeof PinRoute
  PinSetupRoute: typeof PinSetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/age': {
      id: '/age'
      path: '/age'
      fullPath: '/age'
      preLoaderRoute: typeof AgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pin': {
      id: '/pin'
      path: '/pin'
      fullPath: '/pin'
      preLoaderRoute: typeof PinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pin-setup': {
      id: '/pin-setup'
      path: '/pin-setup'
      fullPath: '/pin-setup'
      preLoaderRoute: typeof PinSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/category': {
      id: '/_app/category'
      path: '/category'
      fullPath: '/category'
      preLoaderRoute: typeof AppCategoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/downloaded': {
      id: '/_app/downloaded'
      path: '/downloaded'
      fullPath: '/downloaded'
      preLoaderRoute: typeof AppDownloadedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explore': {
      id: '/_app/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/favorites': {
      id: '/_app/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AppFavoritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboard': {
      id: '/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/liked': {
      id: '/_app/liked'
      path: '/liked'
      fullPath: '/liked'
      preLoaderRoute: typeof AppLikedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-courses': {
      id: '/_app/my-courses'
      path: '/my-courses'
      fullPath: '/my-courses'
      preLoaderRoute: typeof AppMyCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/redeem': {
      id: '/_app/redeem'
      path: '/redeem'
      fullPath: '/redeem'
      preLoaderRoute: typeof AppRedeemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/redeem-history': {
      id: '/_app/redeem-history'
      path: '/redeem-history'
      fullPath: '/redeem-history'
      preLoaderRoute: typeof AppRedeemHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reels': {
      id: '/_app/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof AppReelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saved': {
      id: '/_app/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AppSavedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shop': {
      id: '/_app/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof AppShopRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/skills': {
      id: '/_app/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AppSkillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/course/$slug': {
      id: '/_app/course/$slug'
      path: '/course/$slug'
      fullPath: '/course/$slug'
      preLoaderRoute: typeof AppCourseSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/creator/$username': {
      id: '/_app/creator/$username'
      path: '/creator/$username'
      fullPath: '/creator/$username'
      preLoaderRoute: typeof AppCreatorUsernameRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/english-course/': {
      id: '/_app/english-course/'
      path: '/english-course'
      fullPath: '/english-course/'
      preLoaderRoute: typeof AppEnglishCourseIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/english-course/$courseId': {
      id: '/_app/english-course/$courseId'
      path: '/english-course/$courseId'
      fullPath: '/english-course/$courseId'
      preLoaderRoute: typeof AppEnglishCourseCourseIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/$id': {
      id: '/admin/users/$id'
      path: '/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AppRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppCategoryRoute: typeof AppCategoryRoute
  AppDownloadedRoute: typeof AppDownloadedRoute
  AppExploreRoute: typeof AppExploreRoute
  AppFavoritesRoute: typeof AppFavoritesRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppHomeRoute: typeof AppHomeRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppLikedRoute: typeof AppLikedRoute
  AppMyCoursesRoute: typeof AppMyCoursesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRedeemRoute: typeof AppRedeemRoute
  AppRedeemHistoryRoute: typeof AppRedeemHistoryRoute
  AppReelsRoute: typeof AppReelsRoute
  AppSavedRoute: typeof AppSavedRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShopRoute: typeof AppShopRoute
  AppSkillsRoute: typeof AppSkillsRoute
  AppCourseSlugRoute: typeof AppCourseSlugRoute
  AppCreatorUsernameRoute: typeof AppCreatorUsernameRoute
  AppEnglishCourseCourseIdRoute: typeof AppEnglishCourseCourseIdRoute
  AppEnglishCourseIndexRoute: typeof AppEnglishCourseIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppCategoryRoute: AppCategoryRoute,
  AppDownloadedRoute: AppDownloadedRoute,
  AppExploreRoute: AppExploreRoute,
  AppFavoritesRoute: AppFavoritesRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppHomeRoute: AppHomeRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppLikedRoute: AppLikedRoute,
  AppMyCoursesRoute: AppMyCoursesRoute,
  AppProfileRoute: AppProfileRoute,
  AppRedeemRoute: AppRedeemRoute,
  AppRedeemHistoryRoute: AppRedeemHistoryRoute,
  AppReelsRoute: AppReelsRoute,
  AppSavedRoute: AppSavedRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShopRoute: AppShopRoute,
  AppSkillsRoute: AppSkillsRoute,
  AppCourseSlugRoute: AppCourseSlugRoute,
  AppCreatorUsernameRoute: AppCreatorUsernameRoute,
  AppEnglishCourseCourseIdRoute: AppEnglishCourseCourseIdRoute,
  AppEnglishCourseIndexRoute: AppEnglishCourseIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUsersIdRoute: typeof AdminUsersIdRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminUsersIdRoute: AdminUsersIdRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AgeRoute: AgeRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  PinRoute: PinRoute,
  PinSetupRoute: PinSetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
